"""Injector base classes and the pipeline-stage taxonomy.

An :class:`Injector` is *middleware* on a single stage of a target AI system's
pipeline. It receives the payload flowing through that stage and returns a
perturbed payload, deterministically driven by a seeded RNG so that every
experiment is reproducible.

Stages model an LLM/RAG/robotics pipeline:

``PROMPT``      the user/system prompt string before the model sees it
``EMBEDDING``   dense vector(s) produced by the embedding model
``RETRIEVAL``   the documents returned by the vector store
``LLM_OUTPUT``  the raw text generated by the model
``SENSOR``      raw sensor readings (robotics / perception)
"""

from __future__ import annotations

import enum
import random
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Any, Dict, Optional


class Stage(str, enum.Enum):
    PROMPT = "prompt"
    EMBEDDING = "embedding"
    RETRIEVAL = "retrieval"
    LLM_OUTPUT = "llm_output"
    SENSOR = "sensor"


@dataclass
class InjectionEvent:
    """A record of a single fault injection, for observability/audit."""

    injector: str
    stage: str
    detail: str
    magnitude: float
    case_id: Optional[str] = None
    meta: Dict[str, Any] = field(default_factory=dict)


class Injector(ABC):
    """Base class for all fault injectors.

    Subclasses set :attr:`stage` and :attr:`name` and implement
    :meth:`_apply`. ``intensity`` (0..1) scales the severity of the fault.
    """

    stage: Stage
    name: str = "injector"

    def __init__(self, intensity: float = 0.5, **params: Any) -> None:
        if not 0.0 <= intensity <= 1.0:
            raise ValueError("intensity must be in [0, 1]")
        self.intensity = float(intensity)
        self.params = params

    # -- public API ---------------------------------------------------------
    def apply(self, payload: Any, rng: random.Random, case_id: Optional[str] = None):
        """Perturb ``payload`` and return ``(new_payload, InjectionEvent | None)``.

        Returns the payload unchanged with ``None`` if the injector elected not
        to fire (e.g. probabilistic gating below intensity).
        """
        result = self._apply(payload, rng)
        if result is None:
            return payload, None
        new_payload, detail, magnitude, meta = result
        event = InjectionEvent(
            injector=self.name,
            stage=self.stage.value,
            detail=detail,
            magnitude=magnitude,
            case_id=case_id,
            meta=meta or {},
        )
        return new_payload, event

    # -- subclass contract --------------------------------------------------
    @abstractmethod
    def _apply(self, payload: Any, rng: random.Random):
        """Return ``(new_payload, detail, magnitude, meta)`` or ``None``."""

    def describe(self) -> Dict[str, Any]:
        return {
            "name": self.name,
            "stage": self.stage.value,
            "intensity": self.intensity,
            "params": self.params,
        }

    def __repr__(self) -> str:  # pragma: no cover - trivial
        return f"<{type(self).__name__} stage={self.stage.value} intensity={self.intensity}>"
